version: '3.4'

services:
  identity:
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__ServiceDiscoveryAddress=http://consul:8500
      - ServiceConfig__ServiceAddress=http://identity:80
      - ServiceConfig__ServiceName=identity
      - ServiceConfig__ServiceId=identity-v1
      - ConnectionStrings__IdentityDb=Server=db;Database=DominicanWhoCodesIdentityDb;User=sa;Password=dominicanWhoCodes(!)App2019;
    ports:
      - "8081:80"

  identitygateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"
  db:
    environment:
      SA_PASSWORD: dominicanWhoCodes(!)App2019
      ACCEPT_EULA: Y
    ports:
    - "1433:1433"
  consul:
    ports:
    - "8500:8500"
